services:
  ganache:
    image: trufflesuite/ganache:latest
    command: --defaultBalanceEther 10000 --gasLimit 10000000 -a 10 --chain.chainId 1337 --chain.networkId 1337 -d --host 0.0.0.0
    ports:
      - "8545:8545"
