# Generated by Django 5.0.4 on 2024-05-15 13:51

from django.db import migrations

from ..management.commands.update_leaderboard_view import (
    MATERIALIZED_VIEW_SQL,
    MATERIALIZED_VIEW_TABLE_NAME,
)


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_alter_period_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=MATERIALIZED_VIEW_SQL,
            reverse_sql=f"DROP MATERIALIZED VIEW IF EXISTS {MATERIALIZED_VIEW_TABLE_NAME};",
        )
    ]
