# Generated by Django 5.0.4 on 2024-05-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_period_activity_period_unique_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True)),
                ("max_points", models.PositiveBigIntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_metadata",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
    ]
