# Generated by Django 5.0.6 on 2024-06-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_add_materialized_view"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
    ]
