# Generated by Django 5.0.6 on 2024-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_activity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
