# Generated by Django 5.0.7 on 2024-07-24 07:20

from django.db import migrations, models

import safe_locking_service.campaigns.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaign_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                storage=safe_locking_service.campaigns.models.get_file_storage,
                upload_to=safe_locking_service.campaigns.models.get_campaign_icon_path,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_promoted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="partner_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="reward_text",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="reward_value",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="safe_app_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
