# Generated by Django 5.0.7 on 2024-07-24 15:13

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_campaign_icon_campaign_is_promoted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressBinaryField(),
        ),
    ]
