# Generated by Django 4.2.10 on 2024-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locking_events", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lockevent",
            index=models.Index(
                fields=["holder", "-timestamp"], name="locking_eve_holder_f0b4de_idx"
            ),
        ),
    ]
