# Generated by Django 4.2.10 on 2024-02-29 16:39

from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("locking_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusEventsIndexer",
            fields=[
                (
                    "contract",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        primary_key=True, serialize=False
                    ),
                ),
                ("deployed_block", models.PositiveIntegerField()),
                ("last_indexed_block", models.PositiveIntegerField()),
            ],
        ),
    ]
