# Generated by Django 5.0.7 on 2024-07-24 15:13

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("locking_events", "0003_ethereumtx_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lockevent",
            name="holder",
            field=gnosis.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="statuseventsindexer",
            name="contract",
            field=gnosis.eth.django.models.EthereumAddressBinaryField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="unlockevent",
            name="holder",
            field=gnosis.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="withdrawnevent",
            name="holder",
            field=gnosis.eth.django.models.EthereumAddressBinaryField(),
        ),
    ]
